### ISSUE TITLE
ConfigMapping introduced in #87 doesn't resolve expressions

### ISSUE THREAD

**Issue by kevinross** [quarkiverse/quarkus-config-extensions#125]
I went down a rabbit hole trying to figure out why the URL retrieved in `Repository::prepareDataSource` was the literal string `${quarkus.datasource.jdbc.url}` instead of the value pointed to by that expression and found that it had _something_ to do with `ConfigMapping`. Not knowing more about smallrye+config and the interplay between those and quarkus (with respect to developing quarkus itself, as opposed to simply using quarkus), I'm at a bit of a loss on *why* that change caused this issue.

This started today, after 1.2.0 was released; one of the only non-dependency-bump changes was that particular PR, which is what pointed me in that direction.

Quarkus: 2.16.3.Final
Smallrye: 2.13.2 (which is specified by the BOM for quarkus, I'm only mentioning it here for completeness)

Reproducer:

* quickstart CLI using quarkus 2.16.3.Final, gradle (although I don't think it matters), with jdbc-postgresql and jdbc-config included (the former with the default version, the latter with version >= 1.2.0)
* add `quarkus.datasource.*` properties somewhere (I tested .env, .properties, and .yml) but *not* using `quarkus.config.source.jdbc.*` (ie jdbc-config pull the values from the main datasource config)
* start the application
* repeat with jdbc-config v1.1.0

**Comment by radcortez** [comment]
A regression in SmallRye Config 2.13.2 is the cause of this. 

The most straightforward workaround is to update SmallRye Config manually in your project to 2.13.3. 

I'm sorry for the inconvenience.

**Comment by kevinross** [comment]
gotcha, I've confirmed that simply bumping the version of smallrye fixes it in my environment, thanks!
