### ISSUE TITLE
Problem with consul when multiple properties-value-keys

### ISSUE THREAD

**Issue by ma9loub** [quarkiverse/quarkus-config-extensions#170]
Hi,
We have a problem with consul config with quarkus when we use multiple properties value keys to have property overriding
`quarkus.consul-config.properties-value-keys: app/conf1,app/conf2,app/conf3`

with this conf in consul
- app/conf1 > app.property: value1
- app/conf2 > app.property: value2
- app/conf3 > app.property: value3

That's I want is conf2 override conf3 and conf1 override conf2 but the order of conf loading is not assured. So sometimes it's conf3 which is loaded or conf2 or conf1

I think it's from ConsulConfigSourceProvider#getConfigSources which use Uni.combine().all() and combine is not keeping the order of unis. Maybe the solution would be to use Uni.join().all() ?

Thanks for your reply

**Comment by ma9loub** [comment]
Hi,
Thanks for your reply, Here ma PR: https://github.com/quarkiverse/quarkus-config-extensions/pull/171

Eventually, I used a linked map to conserve ordering of config sources

**Comment by radcortez** [comment]
Great. Thank you. Waiting for CI.
