### ISSUE TITLE
Jasypt encrypted value in Quarkus Profiles can not be read normally

### ISSUE THREAD

**Issue by pengxo** [quarkiverse/quarkus-config-extensions#231]
We use the jasypt encryption for splunk configurations and store the encrypted values in the profile like (`${jasypt::ENC(...)}`). When the encrypted value is assigned directly to the splunk property using the splunk extension (See https://docs.quarkiverse.io/quarkus-logging-splunk/dev/index.html), the encrypted value can be decrypted and read normally. When the encrypted value is assigned through another   property in the profile.  The encrypted value cannot be read normally. The value `ENC(...)` will be used directly. 

For example, we have:
 `quarkus.log.handler.splunk.url=${splunk.logging.url}` 
and
`splunk.logging.url=${jasypt::ENC(...)}`

In this case, the value `ENC(...)` is read directly instead of the decrypted value. By debugging in the code, it seems that the method `io.smallrye.config.SecretKeysHandlerConfigSourceInterceptor.getValue()` gets the value `${splunk.logging.url}` directly instead of the value `${jasypt::ENC(...)}`, which leads to the fact that the `jasypt` handler `JasyptSecretKeysHandler` could not be found and therefore the value could not be decrypted normally.

**Comment by radcortez** [comment]
I'll have a look. I believe this might be related to https://github.com/smallrye/smallrye-config/issues/921.

For now, can you avoid mixing expressions with secret keys?

**Comment by pengxo** [comment]
Yes, we just choose to use environment variables as we don't want to have plain text for splunk configurations in the profiles.

**Comment by radcortez** [comment]
https://github.com/smallrye/smallrye-config/pull/1143 should fix this.

**Comment by radcortez** [comment]
Fixed by the update in https://github.com/quarkiverse/quarkus-config-extensions/pull/242/
