### ISSUE TITLE
quarkus-config-jdbc: Remove print stack trace from Repository#getAllConfigValues

### ISSUE THREAD

**Issue by alex-kovalenko1982** [quarkiverse/quarkus-config-extensions#268]
https://github.com/quarkiverse/quarkus-config-extensions/blob/514e48797d24a2bf867f705d176fca8284f3fbbb/jdbc/runtime/src/main/java/io/quarkiverse/config/jdbc/runtime/Repository.java#L47

All the other repository methods just do `log.trace` in case of the exception but `getAllConfigValues` prints the stack trace additionally. Please remove this printing to be consistent. 

In some use cases it is even valid to have an exception when fetching configuration table. For instance, when tables are created by liquibase and/or hibernate and this step happens after the first call to the config sources.

**Comment by radcortez** [comment]
Yes, that shouldn't be there... just leftovers of some testing code. Can you open a PR to remove it? Thanks!
