### ISSUE TITLE
config-jdbc causing failed maven reactor build with (No suitable driver)

### ISSUE THREAD

**Issue by aster-phoenix** [quarkiverse/quarkus-config-extensions#44]
```
- project-1
|
|--lib-1
|--app-1
|--app-2
```
`project-1` set as parent for all of `lib-1` ,  `app-1` & `app-2`
`config-jdbc` extention defined in `project-1`'s `pom.xml`
`datasource` is defined in `lib-1`'s `application.properties`
`lib-1` standalone mvn build works fine

`app-1` depends on `lib-1`
`app-1` standalone mvn build works fine

`app-2` depends on `lib-1`
`app-2` standalone mvn build works fine

`project-1` reactor mvn build fails on `app-1` (passes `lib-1`) with
java.lang.RuntimeException: Unable to get java.sql.Driver from DriverManager: No suitable driver

if `quarkus-maven-plugin` is disabled in `lib-1`'s `pom.xml` then
`project-1` reactor mvn build fails on app-2 (passes `lib-1` & `app-1`) with
java.lang.RuntimeException: Unable to get java.sql.Driver from DriverManager: No suitable driver

maybe `config-jdbc` can only be initialized once?

Quarkus `2.6.1-Final`
config-jdbc `1.0.1`
OpenJDK `11.0.13`
Maven `3.8.1`

**Comment by aster-phoenix** [comment]
Maybe it's related to this https://github.com/quarkusio/quarkus/blob/2cbd177416f92b9f45abb34b6f01acb8cb0f4eb5/independent-projects/bootstrap/core/src/main/java/io/quarkus/bootstrap/classloading/DriverRemover.java

**Comment by gsmet** [comment]
If I were you, I would prepare a reproducer with H2. That might make it easier for us to reproduce.

**Comment by aster-phoenix** [comment]
Hi @gsmet
I have prepared reproducer, it can be found here
https://github.com/aster-phoenix/quarkus-config-jdbc-example

maven build on individual modules work
maven reactor build fails on app-1
maven reactor build fails on app-2 - when disabling quarkus plugin in lib-1 (uncomment lines 15-24 in  lib-1/pom.xml)

Let me know if you need anything
Thanks for your time and support!

**Comment by radcortez** [comment]
Thanks @aster-phoenix. I'll have a look.

**Comment by radcortez** [comment]
The issue is the jdbc source being registered (and the driver) during build time, which I believe doesn't make much sense. I've submitted a PR to only register the source in static and runtime, which should fix the issue. 

@aster-phoenix do you have any chance to try it out? Thanks!

**Comment by aster-phoenix** [comment]
@radcortez just tested it, It is fixed! 👍

**Comment by radcortez** [comment]
Great. Thanks!
